version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_DB=elasticsearch
      - POSTGRES_HOST=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    expose:
      - "5050"
    ports:
      - 5050:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=adminadmin'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  elastic_search:
    image: elasticsearch:7.17.8
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  django:
    image: django-app
    build: ./
    ports:
      - 8000:8000
    environment:
      DEBUG: 'true'  
    command: >
      sh -c "python elastic_search/manage.py makemigrations &&
             python elastic_search/manage.py migrate &&
             python elastic_search/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
      - elastic_search
volumes:
  pgadmin-data:
    driver: local
  db-data:
    driver: local
  elasticsearch-data:
    driver: local
      